language: csharp

os:
 - linux

dist: xenial

mono: none
dotnet: 2.1.3

before_install:
 - cd scripts
 - chmod +x *.sh
 - sudo apt-get update
 - sudo apt-get install binutils binutils-multiarch g++-multilib

script:
 - ./test.sh
