language: csharp

os:
 - linux

dist: xenial

dotnet: 2.1.300
mono: none

before_install:
 - cd scripts
 - chmod +x *.sh
 - sudo apt-get update
 - sudo apt-get install binutils binutils-multiarch g++-multilib

script:
 - ./testAndCompile.sh
