language: csharp

os:
 - linux
 - osx

matrix:
  include:
    - os: linux
      dist: xenial
      dotnet: 2.1.300
      mono: none
    - os: osx
      osx_image: xcode9.4
      dotnet: 2.1.300
      mono: none


addons:
  apt:
    packages:
      - binutils
      - binutils-multiarch
      - g++-multilib

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; sudo apt-get update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; sudo apt-get install binutils binutils-multiarch g++-multilib; fi

script:
 - cd scripts
 - ./testAndCompile.sh
