language: csharp

os:
 - linux
 - osx

dist: xenial
sudo: required
dotnet: 2.1.300
mono: none

addons:
  apt:
    packages:
      - binutils
      - binutils-multiarch
      - g++-multilib

script:
 - cd scripts
 - ./testAndCompile.sh
